### ISSUE TITLE
C++ Error - corrupted size vs. prev_size

### ISSUE THREAD

**Issue by ypy-pasha** [smartmontools/smartmontools#233]
```
root@xxxx:~# smartctl /dev/nvme0n1 --all -j >&1
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      2
    ],
    "svn_revision": "5155",
    "platform_info": "x86_64-linux-6.2.0-39-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "--all",
      "/dev/nvme0n1",
      "-j"
    ],
    "exit_status": 0
  },
  "device": {
    "name": "/dev/nvme0n1",
    "info_name": "/dev/nvme0n1",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "Kingmax PCIe SSD 256GB",
  "serial_number": "xxxxx",
  "firmware_version": "V1.6.C2",
  "nvme_pci_vendor": {
    "id": 7575,
    "subsystem_id": 7575
  },
  "nvme_ieee_oui_identifier": 3824167,
  "nvme_total_capacity": 256060514304,
  "nvme_unallocated_capacity": 0,
  "nvme_controller_id": 0,
  "nvme_version": {
    "string": "1.4",
    "value": 66560
  },
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 500118192,
        "bytes": 256060514304
      },
      "capacity": {
        "blocks": 500118192,
        "bytes": 256060514304
      },
      "utilization": {
        "blocks": 500118192,
        "bytes": 256060514304
      },
      "formatted_lba_size": 512,
      "eui64": {
        "oui": 3824167,
        "ext_id": 15837737524
      }
    }
  ],
  "user_capacity": {
    "blocks": 500118192,
    "bytes": 256060514304
  },
  "logical_block_size": 512,
  "local_time": {
    "time_t": 1703927422,
    "asctime": "Sat Dec 30 12:40:22 2023 +0330"
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 45,
    "available_spare": 100,
    "available_spare_threshold": 10,
    "percentage_used": 2,
    "data_units_read": 1545776,
    "data_units_written": 2307039,
    "host_reads": 15630153,
    "host_writes": 17841168,
    "controller_busy_time": 49,
    "power_cycles": 109,
    "power_on_hours": 263,
    "unsafe_shutdowns": 27,
    "media_errors": 0,
    "num_err_log_entries": 0,
    "warning_temp_time": 0,
    "critical_comp_time": 0
  },
  "temperature": {
    "current": 45
  },
  "power_cycle_count": 109,
  "power_on_time": {
    "hours": 263
  }
}
corrupted size vs. prev_size
Aborted (core dumped)

```
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by chrfranke** [comment]
The `corrupted size vs. prev_size` message is from glibc which suggests memory corruption.
Does this problem also occur with other drives?

Please try `smartctl --json=g -x /dev/nvme0n1` and `smartctl --json=y -x /dev/nvme0n1`

**Comment by ypy-pasha** [comment]
> The `corrupted size vs. prev_size` message is from glibc which suggests memory corruption. Does this problem also occur with other drives?
> 
> Please try `smartctl --json=g -x /dev/nvme0n1` and `smartctl --json=y -x /dev/nvme0n1`

no, just these devices nvme type.

```
root@xxx:~# smartctl --json=g -x --all /dev/nvme0n1
json = {};
json.json_format_version = [];
json.json_format_version[0] = 1;
json.json_format_version[1] = 0;
json.smartctl = {};
json.smartctl.version = [];
json.smartctl.version[0] = 7;
json.smartctl.version[1] = 2;
json.smartctl.svn_revision = "5155";
json.smartctl.platform_info = "x86_64-linux-6.2.0-39-generic";
json.smartctl.build_info = "(local build)";
json.smartctl.argv = [];
json.smartctl.argv[0] = "smartctl";
json.smartctl.argv[1] = "--json=g";
json.smartctl.argv[2] = "-x";
json.smartctl.argv[3] = "--all";
json.smartctl.argv[4] = "/dev/nvme0n1";
json.smartctl.exit_status = 0;
json.device = {};
json.device.name = "/dev/nvme0n1";
json.device.info_name = "/dev/nvme0n1";
json.device.type = "nvme";
json.device.protocol = "NVMe";
json.model_name = "Kingmax PCIe SSD 256GB";
json.serial_number = "xxxx";
json.firmware_version = "V1.6.C2";
json.nvme_pci_vendor = {};
json.nvme_pci_vendor.id = 7575;
json.nvme_pci_vendor.subsystem_id = 7575;
json.nvme_ieee_oui_identifier = 3824167;
json.nvme_total_capacity = 256060514304;
json.nvme_unallocated_capacity = 0;
json.nvme_controller_id = 0;
json.nvme_version = {};
json.nvme_version.string = "1.4";
json.nvme_version.value = 66560;
json.nvme_number_of_namespaces = 1;
json.nvme_namespaces = [];
json.nvme_namespaces[0] = {};
json.nvme_namespaces[0].id = 1;
json.nvme_namespaces[0].size = {};
json.nvme_namespaces[0].size.blocks = 500118192;
json.nvme_namespaces[0].size.bytes = 256060514304;
json.nvme_namespaces[0].capacity = {};
json.nvme_namespaces[0].capacity.blocks = 500118192;
json.nvme_namespaces[0].capacity.bytes = 256060514304;
json.nvme_namespaces[0].utilization = {};
json.nvme_namespaces[0].utilization.blocks = 500118192;
json.nvme_namespaces[0].utilization.bytes = 256060514304;
json.nvme_namespaces[0].formatted_lba_size = 512;
json.nvme_namespaces[0].eui64 = {};
json.nvme_namespaces[0].eui64.oui = 3824167;
json.nvme_namespaces[0].eui64.ext_id = 15837737524;
json.user_capacity = {};
json.user_capacity.blocks = 500118192;
json.user_capacity.bytes = 256060514304;
json.logical_block_size = 512;
json.local_time = {};
json.local_time.time_t = 1705155446;
json.local_time.asctime = "Sat Jan 13 17:47:26 2024 +0330";
json.smart_status = {};
json.smart_status.passed = true;
json.smart_status.nvme = {};
json.smart_status.nvme.value = 0;
json.nvme_smart_health_information_log = {};
json.nvme_smart_health_information_log.critical_warning = 0;
json.nvme_smart_health_information_log.temperature = 46;
json.nvme_smart_health_information_log.available_spare = 100;
json.nvme_smart_health_information_log.available_spare_threshold = 10;
json.nvme_smart_health_information_log.percentage_used = 2;
json.nvme_smart_health_information_log.data_units_read = 1738073;
json.nvme_smart_health_information_log.data_units_written = 2680815;
json.nvme_smart_health_information_log.host_reads = 17706764;
json.nvme_smart_health_information_log.host_writes = 21114867;
json.nvme_smart_health_information_log.controller_busy_time = 53;
json.nvme_smart_health_information_log.power_cycles = 126;
json.nvme_smart_health_information_log.power_on_hours = 341;
json.nvme_smart_health_information_log.unsafe_shutdowns = 27;
json.nvme_smart_health_information_log.media_errors = 0;
json.nvme_smart_health_information_log.num_err_log_entries = 0;
json.nvme_smart_health_information_log.warning_temp_time = 0;
json.nvme_smart_health_information_log.critical_comp_time = 0;
json.temperature = {};
json.temperature.current = 46;
json.power_cycle_count = 126;
json.power_on_time = {};
json.power_on_time.hours = 341;
free(): invalid pointer
Aborted (core dumped)

```


```
root@xxx:~# smartctl --json=g -x  /dev/nvme0n1
json = {};
json.json_format_version = [];
json.json_format_version[0] = 1;
json.json_format_version[1] = 0;
json.smartctl = {};
json.smartctl.version = [];
json.smartctl.version[0] = 7;
json.smartctl.version[1] = 2;
json.smartctl.svn_revision = "5155";
json.smartctl.platform_info = "x86_64-linux-6.2.0-39-generic";
json.smartctl.build_info = "(local build)";
json.smartctl.argv = [];
json.smartctl.argv[0] = "smartctl";
json.smartctl.argv[1] = "--json=g";
json.smartctl.argv[2] = "-x";
json.smartctl.argv[3] = "/dev/nvme0n1";
json.smartctl.exit_status = 0;
json.device = {};
json.device.name = "/dev/nvme0n1";
json.device.info_name = "/dev/nvme0n1";
json.device.type = "nvme";
json.device.protocol = "NVMe";
json.model_name = "Kingmax PCIe SSD 256GB";
json.serial_number = "xxxx";
json.firmware_version = "V1.6.C2";
json.nvme_pci_vendor = {};
json.nvme_pci_vendor.id = 7575;
json.nvme_pci_vendor.subsystem_id = 7575;
json.nvme_ieee_oui_identifier = 3824167;
json.nvme_total_capacity = 256060514304;
json.nvme_unallocated_capacity = 0;
json.nvme_controller_id = 0;
json.nvme_version = {};
json.nvme_version.string = "1.4";
json.nvme_version.value = 66560;
json.nvme_number_of_namespaces = 1;
json.nvme_namespaces = [];
json.nvme_namespaces[0] = {};
json.nvme_namespaces[0].id = 1;
json.nvme_namespaces[0].size = {};
json.nvme_namespaces[0].size.blocks = 500118192;
json.nvme_namespaces[0].size.bytes = 256060514304;
json.nvme_namespaces[0].capacity = {};
json.nvme_namespaces[0].capacity.blocks = 500118192;
json.nvme_namespaces[0].capacity.bytes = 256060514304;
json.nvme_namespaces[0].utilization = {};
json.nvme_namespaces[0].utilization.blocks = 500118192;
json.nvme_namespaces[0].utilization.bytes = 256060514304;
json.nvme_namespaces[0].formatted_lba_size = 512;
json.nvme_namespaces[0].eui64 = {};
json.nvme_namespaces[0].eui64.oui = 3824167;
json.nvme_namespaces[0].eui64.ext_id = 15837737524;
json.user_capacity = {};
json.user_capacity.blocks = 500118192;
json.user_capacity.bytes = 256060514304;
json.logical_block_size = 512;
json.local_time = {};
json.local_time.time_t = 1705155493;
json.local_time.asctime = "Sat Jan 13 17:48:13 2024 +0330";
json.smart_status = {};
json.smart_status.passed = true;
json.smart_status.nvme = {};
json.smart_status.nvme.value = 0;
json.nvme_smart_health_information_log = {};
json.nvme_smart_health_information_log.critical_warning = 0;
json.nvme_smart_health_information_log.temperature = 46;
json.nvme_smart_health_information_log.available_spare = 100;
json.nvme_smart_health_information_log.available_spare_threshold = 10;
json.nvme_smart_health_information_log.percentage_used = 2;
json.nvme_smart_health_information_log.data_units_read = 1738073;
json.nvme_smart_health_information_log.data_units_written = 2680828;
json.nvme_smart_health_information_log.host_reads = 17706764;
json.nvme_smart_health_information_log.host_writes = 21115255;
json.nvme_smart_health_information_log.controller_busy_time = 53;
json.nvme_smart_health_information_log.power_cycles = 126;
json.nvme_smart_health_information_log.power_on_hours = 341;
json.nvme_smart_health_information_log.unsafe_shutdowns = 27;
json.nvme_smart_health_information_log.media_errors = 0;
json.nvme_smart_health_information_log.num_err_log_entries = 0;
json.nvme_smart_health_information_log.warning_temp_time = 0;
json.nvme_smart_health_information_log.critical_comp_time = 0;
json.temperature = {};
json.temperature.current = 46;
json.power_cycle_count = 126;
json.power_on_time = {};
json.power_on_time.hours = 341;
corrupted size vs. prev_size
Aborted (core dumped)
```

**Comment by chrfranke** [comment]
> `smartctl 7.2 2020-12-30 r5155 [x86_64-linux-6.2.0-39-generic] (local build)`

This version is now 3+ years old and NVMe and JSON related code has been changed since then.
If possible, please retry with a recent CI build from https://builds.smartmontools.org/.

**Comment by fufler** [comment]
Hello everyone. I experience the same issue with  smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.7.2-arch1-2]. What additional information should I provide to help to identify the issue?

**Comment by chrfranke** [comment]
Please check which minimal subset of options from `-j -i -H -A -l error -l selftest` produces the error and provide a sample output of this case.

**Comment by fufler** [comment]
@chrfranke Sorry for slow response, I've missed notification about your message. Here is the output:

```json
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      4
    ],
    "pre_release": false,
    "svn_revision": "5530",
    "platform_info": "x86_64-linux-6.7.2-arch1-2",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-j",
      "-i",
      "-H",
      "-A",
      "-l",
      "error",
      "-l",
      "selftest",
      "/dev/nvme0"
    ],
    "exit_status": 0
  },
  "local_time": {
    "time_t": 1707848373,
    "asctime": "Tue Feb 13 21:19:33 2024 MSK"
  },
  "device": {
    "name": "/dev/nvme0",
    "info_name": "/dev/nvme0",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "ADATA SX6000LNP",
  "serial_number": "2M3529182A2C",
  "firmware_version": "VC0S036H",
  "nvme_pci_vendor": {
    "id": 7361,
    "subsystem_id": 7361
  },
  "nvme_ieee_oui_identifier": 7371800,
  "nvme_controller_id": 1,
  "nvme_version": {
    "string": "1.4",
    "value": 66560
  },
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 250069680,
        "bytes": 128035676160
      },
      "capacity": {
        "blocks": 250069680,
        "bytes": 128035676160
      },
      "utilization": {
        "blocks": 250069680,
        "bytes": 128035676160
      },
      "formatted_lba_size": 512,
      "eui64": {
        "oui": 7371800,
        "ext_id": 476511234000
      }
    }
  ],
  "user_capacity": {
    "blocks": 250069680,
    "bytes": 128035676160
  },
  "logical_block_size": 512,
  "smart_support": {
    "available": true,
    "enabled": true
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 46,
    "available_spare": 100,
    "available_spare_threshold": 32,
    "percentage_used": 13,
    "data_units_read": 618708,
    "data_units_written": 11015740,
    "host_reads": 19010072,
    "host_writes": 459513442,
    "controller_busy_time": 0,
    "power_cycles": 42,
    "power_on_hours": 714,
    "unsafe_shutdowns": 32,
    "media_errors": 0,
    "num_err_log_entries": 0,
    "warning_temp_time": 0,
    "critical_comp_time": 0
  },
  "temperature": {
    "current": 46
  },
  "power_cycle_count": 42,
  "power_on_time": {
    "hours": 714
  },
  "nvme_error_information_log": {
    "size": 8,
    "read": 8,
    "unread": 0
  },
  "nvme_self_test_log": {
    "current_self_test_operation": {
      "value": 0,
      "string": "No self-test in progress"
    }
  }
}
```

**Comment by chrfranke** [comment]
@fufler Does the above output mean that
`  smartctl -j -i -H -A -l error -l selftest /dev/nvme0`
produces the `corrupted ...` message, but removing any of `-i`, `-H`, `-A`, `-l error` or `-l selftest` does not?

**Comment by fufler** [comment]
@chrfranke No, `smartctl -j -i -H -A -l error -l selftest /dev/nvme0` runs without errors and produces the output I've posted in previous message. I think I was not correct originally saying that I was having the same issue. The crash is produced by prometheus smartctl exporter that runs [this command](https://github.com/prometheus-community/smartctl_exporter/blob/master/readjson.go#L67). If I remove any of the following argumens 

```
--json
--tolerance=verypermissive
--nocheck=standby
--format=brief
--log=error
```

smartctl executes successfully without crash. I've checked it multiple times. If you need I may run smarctl with gdb or valgrind to produce more information for debug.

**Comment by samm-git** [comment]
@fufler sorry for the late reply. GDB stacktrace would be very helpful

**Comment by fufler** [comment]
@samm-git Here is failure stacktrace

```
gdb$ r
Starting program: /usr/bin/smartctl --json --info --health --attributes --tolerance=verypermissive --nocheck=standby --format=brief --log=error /dev/nvme0

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      4
    ],
    "pre_release": false,
    "svn_revision": "5530",
    "platform_info": "x86_64-linux-6.7.8-arch1-1",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "--json",
      "--info",
      "--health",
      "--attributes",
      "--tolerance=verypermissive",
      "--nocheck=standby",
      "--format=brief",
      "--log=error",
      "/dev/nvme0"
    ],
    "exit_status": 0
  },
  "local_time": {
    "time_t": 1709571608,
    "asctime": "Mon Mar  4 20:00:08 2024 MSK"
  },
  "device": {
    "name": "/dev/nvme0",
    "info_name": "/dev/nvme0",
    "type": "nvme",
    "protocol": "NVMe"
  },
  "model_name": "ADATA SX6000LNP",
  "serial_number": "2M3529182A2C",
  "firmware_version": "VC0S036H",
  "nvme_pci_vendor": {
    "id": 7361,
    "subsystem_id": 7361
  },
  "nvme_ieee_oui_identifier": 7371800,
  "nvme_controller_id": 1,
  "nvme_version": {
    "string": "1.4",
    "value": 66560
  },
  "nvme_number_of_namespaces": 1,
  "nvme_namespaces": [
    {
      "id": 1,
      "size": {
        "blocks": 250069680,
        "bytes": 128035676160
      },
      "capacity": {
        "blocks": 250069680,
        "bytes": 128035676160
      },
      "utilization": {
        "blocks": 250069680,
        "bytes": 128035676160
      },
      "formatted_lba_size": 512,
      "eui64": {
        "oui": 7371800,
        "ext_id": 476511234000
      }
    }
  ],
  "user_capacity": {
    "blocks": 250069680,
    "bytes": 128035676160
  },
  "logical_block_size": 512,
  "smart_support": {
    "available": true,
    "enabled": true
  },
  "smart_status": {
    "passed": true,
    "nvme": {
      "value": 0
    }
  },
  "nvme_smart_health_information_log": {
    "critical_warning": 0,
    "temperature": 44,
    "available_spare": 100,
    "available_spare_threshold": 32,
    "percentage_used": 13,
    "data_units_read": 668355,
    "data_units_written": 11370192,
    "host_reads": 20538864,
    "host_writes": 474124251,
    "controller_busy_time": 0,
    "power_cycles": 44,
    "power_on_hours": 741,
    "unsafe_shutdowns": 34,
    "media_errors": 0,
    "num_err_log_entries": 0,
    "warning_temp_time": 0,
    "critical_comp_time": 0
  },
  "temperature": {
    "current": 44
  },
  "power_cycle_count": 44,
  "power_on_time": {
    "hours": 741
  },
  "nvme_error_information_log": {
    "size": 8,
    "read": 8,
    "unread": 0
  }
}
corrupted size vs. prev_size

Program received signal SIGABRT, Aborted.
-----------------------------------------------------------------------------------------------------------------------[code]
=> 0x7ffff7aab32c:      mov    ebx,eax
   0x7ffff7aab32e:      neg    ebx
   0x7ffff7aab330:      cmp    eax,0xfffff000
   0x7ffff7aab335:      mov    eax,0x0
   0x7ffff7aab33a:      cmova  eax,ebx
   0x7ffff7aab33d:      jmp    0x7ffff7aab2ba
   0x7ffff7aab342:      nop    WORD PTR [rax+rax*1+0x0]
   0x7ffff7aab348:      mov    rdi,r12
-----------------------------------------------------------------------------------------------------------------------------
0x00007ffff7aab32c in ?? () from /usr/lib/libc.so.6
gdb$ bt
#0  0x00007ffff7aab32c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7a5a6c8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff7a424b8 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7a43395 in ?? () from /usr/lib/libc.so.6
#4  0x00007ffff7ab52a7 in ?? () from /usr/lib/libc.so.6
#5  0x00007ffff7ab5dfe in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff7ab5f70 in ?? () from /usr/lib/libc.so.6
#7  0x00007ffff7ab6fdd in ?? () from /usr/lib/libc.so.6
#8  0x00007ffff7ab9e93 in free () from /usr/lib/libc.so.6
#9  0x00005555555d1242 in std::__new_allocator<drive_settings>::deallocate (this=0x55555567f830 <knowndrives+16>, __p=0x555555732970, __n=0x400) at /usr/include/c++/13.2.1/bits/new_allocator.h:168
#10 0x00005555555d01a6 in std::allocator_traits<std::allocator<drive_settings> >::deallocate (__n=0x400, __p=0x555555732970, __a=...) at /usr/include/c++/13.2.1/bits/alloc_traits.h:516
#11 std::_Vector_base<drive_settings, std::allocator<drive_settings> >::_M_deallocate (this=0x55555567f830 <knowndrives+16>, __p=0x555555732970, __n=0x400) at /usr/include/c++/13.2.1/bits/stl_vector.h:387
#12 0x00005555555cfd9d in std::_Vector_base<drive_settings, std::allocator<drive_settings> >::~_Vector_base (this=0x55555567f830 <knowndrives+16>, __in_chrg=<optimized out>) at /usr/include/c++/13.2.1/bits/stl_vector.h:366
#13 0x00005555555cfdff in std::vector<drive_settings, std::allocator<drive_settings> >::~vector (this=0x55555567f830 <knowndrives+16>, __in_chrg=<optimized out>) at /usr/include/c++/13.2.1/bits/stl_vector.h:735
#14 0x00005555555ccb69 in drive_database::~drive_database (this=0x55555567f820 <knowndrives>, __in_chrg=<optimized out>) at knowndrives.cpp:99
#15 0x00007ffff7a5cb36 in ?? () from /usr/lib/libc.so.6
#16 0x00007ffff7a5cc80 in exit () from /usr/lib/libc.so.6
#17 0x00007ffff7a43cd7 in ?? () from /usr/lib/libc.so.6
#18 0x00007ffff7a43d8a in __libc_start_main () from /usr/lib/libc.so.6
#19 0x00005555555828e5 in _start ()
gdb$
```

By the way it's quite strange that smartcl does not fail when run under valgrind:

```
==6822== 
==6822== HEAP SUMMARY:
==6822==     in use at exit: 0 bytes in 0 blocks
==6822==   total heap usage: 103,648 allocs, 103,648 frees, 9,526,517 bytes allocated
==6822== 
==6822== All heap blocks were freed -- no leaks are possible
==6822== 
==6822== For lists of detected and suppressed errors, rerun with: -s
==6822== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by osamorukov-nex** [comment]
Thank you. This is really strange and suspicious. I suspect it could be some strange compiler madness. Could you please try if issue is reproducible with latest build from the https://builds.smartmontools.org/ ?

**Comment by samm-git** [comment]
This is strange and suspicious and could be a compiler bug. Could you please try to reproduce it using build from the https://builds.smartmontools.org/ ?

**Comment by fufler** [comment]
I've built smartmontools 7.4 with both g++ and clang++ using -O0 and -g, both version fail to run. What exactly do you want me to reproduce? Should I compile the latest version available? If we suspect some compiler madness here then I would expect libc build to be affected rather then smartmontools.

**Comment by fufler** [comment]
Actually there is a problem with broken links at https://builds.smartmontools.org/. I've tried to download some binaries and sources, but with no luck. Every link gives me 404 error.

**Comment by samm-git** [comment]
@fufler thank you for report. Builds expired. I re-run the latest build, so it should be fine now. Please try if you can reproduce error on the latest build, static and from the source code. Thank you

**Comment by fufler** [comment]
@samm-git dev  build work just fine. Tried 4 different variants: {pre-compiled static binaries, source code } × {clang, gcc}. I'll keep an eye on package from Arch repositories and let know if there are any new problems after package upgrade is done by maintainer.

**Comment by samm-git** [comment]
@fufler thank you very much for such extensive testing. 

what is really strange - I was not able to reproduce this bug in qemu with a virtual nvme disk using the same version as a topic starter has. Lets keep open this ticket for some time to see if there is anyone with similar issue.

**Comment by fufler** [comment]
@samm-git I have some other devices with nvmde drives. I'll try to reproduce issue and come back with results.
